# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"3\n\tHoneypots\x12\x17\n\x0fHoneypotsAsJSON\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\r2;\n\x0bQueryServer\x12,\n\x0cGetHoneypots\x12\x0b.grpc.Empty\x1a\x0f.grpc.Honeypotsb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_HONEYPOTS = DESCRIPTOR.message_types_by_name['Honeypots']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

Honeypots = _reflection.GeneratedProtocolMessageType('Honeypots', (_message.Message,), {
  'DESCRIPTOR' : _HONEYPOTS,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Honeypots)
  })
_sym_db.RegisterMessage(Honeypots)

_QUERYSERVER = DESCRIPTOR.services_by_name['QueryServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=21
  _EMPTY._serialized_end=28
  _HONEYPOTS._serialized_start=30
  _HONEYPOTS._serialized_end=81
  _QUERYSERVER._serialized_start=83
  _QUERYSERVER._serialized_end=142
# @@protoc_insertion_point(module_scope)
